name: test-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source code
      if: github.event_name == 'push'
      uses: actions/checkout@v2
    - name: Checkout Source code
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: DoozyX/clang-format-lint-action@v0.9
      with:
        source: './src'
        #exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: file
