name: test-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.9
      with:
        source: './src'
        #exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: mozilla
